### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by xinye01234** [Nightmayr-snaps/yuzu-snap#21]
xinye@xinye-PC:~/Desktop$ snap run yuzu
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

help！

**Comment by Nightmayr** [comment]
Can you please provide more details? 

- Distro being used and version  (e.g Ubuntu 20.04)?
- GPU information (Nvidia/AMD ?)
- Xorg or Wayland?
- Do you experience similar errors when running other Games/Emulators?

**Comment by Nightmayr** [comment]
No further information, so closing this issue
