### ISSUE TITLE
Could this be problematic in the future?

### ISSUE THREAD

**Issue by iMonZ** [Nightmayr-snaps/yuzu-snap#29]
Hey i am currently using Ubuntu 21.04 with wayland and get this warnings:

Gtk-Message: 09:51:25.554: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:51:25.555: Failed to load module "canberra-gtk-module"
/usr/share/libdrm/amdgpu.ids: No such file or directory
Qt: Session management error: Could not open network socket

Could this be problematic in the future?

I could remove this warning with the amdgpu.ids with this environment variable: DRI_PRIME=1
But after that I get this warnings:

DRI_PRIME=1 yuzu                         2.3m  Di 23 Feb 2021 09:53:38 CET
libGL error: Different GPU, but blitImage not implemented for this driver
libGL error: failed to load driver: i965
Gtk-Message: 09:53:44.870: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:53:44.871: Failed to load module "canberra-gtk-module"
libGL error: Different GPU, but blitImage not implemented for this driver
libGL error: failed to load driver: i965
Qt: Session management error: Could not open network socket

In the top bar I get 128 Not found instead of the application name

**Comment by Nightmayr** [comment]
Hey, I've got a fix for the amdgpu.ids file. The fix should be in the edge channel (`snap refresh yuzu --edge`). Let me know if this fixes the problem for you.

I'm not too sure what's changed recently to cause the title bar to no longer display the version as this was working approximately 2 weeks ago. I'll do some investigating and see whether the yuzu team can advise.

**Comment by iMonZ** [comment]
> Hey, I've got a fix for the amdgpu.ids file. The fix should be in the edge channel (`snap refresh yuzu --edge`). Let me know if this fixes the problem for you.
> 
> I'm not too sure what's changed recently to cause the title bar to no longer display the version as this was working approximately 2 weeks ago. I'll do some investigating and see whether the yuzu team can advise.

Hey thanks the amdgpu.ids issue is gone!
Before we proceed to the yuzu team I need to advice you that i'm not using the stable version of my operating system! 
Can you tell me how to build a "edge" or "beta" build from the snap source code? Currently I'm new into snap

**Comment by Nightmayr** [comment]
The snap should behave the same on 21.04 as it does on 20.04. I'm seeing the same 128-NOT-FOUND on 20.04. This issue doesn't appear when I compile yuzu without snap. Might sugggest the problem is either with a code change in yuzu or snapcraft.

If you want to build the snap, you'll need to install 2 other snaps to build it. *snapcraft* and *multipass*.
`snap install snapcraft --classic`
`snap install multipass`

When you have those 2 snaps installed, clone this repo and run `snapcraft` when you're in the top level directory. It should create a snap file which you can install using `snap install file.snap --dangerous` where `file.snap` will be the name of the snap file created. To revert back to yuzu from the snap-store run `snap refresh yuzu --amend`

If you want to experiment with some changes then I'd recommend building with `snapcraft --debug` as that places you in the build VM if the build wasn't successful so you can inspect what may have caused a failure.

The "edge" build currently I have it set up so that it builds pull requests and the master branch reflects the stable channel.

**Comment by iMonZ** [comment]
> The snap should behave the same on 21.04 as it does on 20.04. I'm seeing the same 128-NOT-FOUND on 20.04. This issue doesn't appear when I compile yuzu without snap. Might sugggest the problem is either with a code change in yuzu or snapcraft.
> 
> 
> 
> If you want to build the snap, you'll need to install 2 other snaps to build it. *snapcraft* and *multipass*.
> 
> `snap install snapcraft --classic`
> 
> `snap install multipass`
> 
> 
> 
> When you have those 2 snaps installed, clone this repo and run `snapcraft` when you're in the top level directory. It should create a snap file which you can install using `snap install file.snap --dangerous` where `file.snap` will be the name of the snap file created. To revert back to yuzu from the snap-store run `snap refresh yuzu --amend`
> 
> 
> 
> If you want to experiment with some changes then I'd recommend building with `snapcraft --debug` as that places you in the build VM if the build wasn't successful so you can inspect what may have caused a failure.
> 
> 
> 
> The "edge" build currently I have it set up so that it builds pull requests and the master branch reflects the stable channel. I'll promote the fix from edge to stable shortly.

Thanks! So there is not command or Build Script to build the edge build directly?

**Comment by Nightmayr** [comment]
No problem, the edge build was built from this pull request: https://github.com/Nightmayr-snaps/yuzu-snap/pull/23, there's a GitHub action (CI/CD job) that automatically builds pull requests and pushes to the edge channel. If you want to build what is currently in the edge channel, switch branch from `master` to `libdrm` via `git checkout libdrm` and then run the build commands in my previous comment.

**Comment by iMonZ** [comment]
> No problem, the edge build was built from this pull request: https://github.com/Nightmayr-snaps/yuzu-snap/pull/23, there's a GitHub action (CI/CD job) that automatically builds pull requests and pushes to the edge channel. If you want to build what is currently in the edge channel, switch branch from `master` to `libdrm` via `git checkout libdrm` and then run the build commands in my previous comment.

Oh got it!
Will try it later today
