### ISSUE TITLE
Unable to open folders

### ISSUE THREAD

**Issue by iMonZ** [Nightmayr-snaps/yuzu-snap#30]
Inside this snap its not possible to open folders in nautilus from the application!

Example: File/Open Yuzu folder does nothing after pressing the button

Ubuntu 21.04 5.10.0-14-generic wayland

**Comment by Nightmayr** [comment]
I believe this may be a result of the application being sandboxed. As far as I'm aware Flatpak also has the same problem, the Citra Flatpak exhibits the same behaviour when trying to open the Citra folder. I think what's required is a code change in yuzu itself to use xdg-desktop-portal but I'm not really experienced in this.

**Comment by iMonZ** [comment]
> I believe this may be a result of the application being sandboxed. As far as I'm aware Flatpak also has the same problem, the Citra Flatpak exhibits the same behaviour when trying to open the Citra folder. I think what's required is a code change in yuzu itself to use xdg-desktop-portal but I'm not really experienced in this.

Thanks!
