### ISSUE TITLE
No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by liberavia** [Nightmayr-snaps/yuzu-snap#33]
Unfortunately the yuzu snap crashes after trying to add a folder or a file. I get the following on the shell then:

```
/usr/share/libdrm/amdgpu.ids: No such file or directory
Gtk-Message: 12:58:54.548: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:58:54.557: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
/usr/share/libdrm/amdgpu.ids: No such file or directory
^C^C
(yuzu:127083): GLib-GIO-ERROR **: 12:59:27.331: No GSettings schemas are installed on the system
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by Nightmayr** [comment]
I'm unable to reproduce this on my system (Ubuntu 20.04). I've taken a look at your PR, normally it would trigger a CI job but that would build the snap which you could download as an artifact for testing, unfortunately this wasn't working quite right yesterday. I created another PR with your changes and the snap was built. You can test the snap by downloading the artifact from here https://github.com/Nightmayr-snaps/yuzu-snap/actions/runs/883671395. If those changes don't fix the issue for you, you can try making additional changes to your PR and it should trigger the build job correctly this time so you should be able to test your changes. To install the snap manually run `snap install --dangerous yuzu-xxx.snap` where yuzu-xxx.snap is the actual downloaded snap.

**Comment by Nightmayr** [comment]
I dont think adding to build packages will show any changes you'll probably want to try adding the non dev package `gsetting-desktop-schemas` to `stage-packages` as this describes the packages bundled into the final snap
