### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by joaorb64** [Nightmayr-snaps/yuzu-snap#38]
I've noticed recently that Yuzu does not output audio using the Snap package. Works using the Appimage.
Some time ago, audio used to work fine using the Snap package.

**Comment by almirferrari** [comment]
I have the same problem. Ubuntu 20.04.

**Comment by Nightmayr** [comment]
Just tested on my system and can confirm I'm not getting audio as well, will investigate this. As mentioned above audio used to work with no problems with the Snap package, and as far as I can tell all depedencies are staged including `libpulse0`

**Comment by Nightmayr** [comment]
There's a new revision in the stable channel `366`. Update to that version and the audio should be fixed for the cubeb and sdl audio backends

**Comment by joaorb64** [comment]
I saw you had the build going, I have it right now and can confirm it's working :D 
Thank you so much!

**Comment by Nightmayr** [comment]
No problem, thanks for making me aware of the problem :)
